api/docker-compose.yaml
api/test/tests/controllers/participant.js
api/test/utils/api.js
package.json

Integrated the API server into the tests as demonstrated in the `participant` tests. It is still suboptimal as you have to have the mongo container running already. 
Definitely need to work of the sketchiness of running all the containers at once. I am trying to get it so that there is a single `docker-compose` file that runs everything and updates with changes. It works for the API but there is a weird bug with the frontend. I think it has to do with where the file is being run from.
Going to add in _redux_ tonight for the frontend.

Integrate API and Tests

---

www/store/client.js
www/store/features/user/userSlice.js

Using a single client will allow us to easily switch between different urls for the api which we will need to do for deployment. Also, for the create meeting page, I might extend this client to have new methods like `authPost` that grabs the **JWT** from the store if there is one and uses it in the `authentication` header of the request.

Axios Client

---

api/lib/controllers/meeting.js
api/lib/controllers/participant.js
api/lib/models/participant.js
api/test/tests/controllers/meeting.js
api/test/tests/controllers/participant.js

Modified the `participant` controllers and model such that they only require `email` and `meeting_id` as well as refactoring the tests to use the Axios `client`.
We don't want to add the participant first name and last name because it will make entering information take longer when creating a meeting with little benefit.

Participant Refactor to Require Email and Meeting ID Only.

---

api/lib/controllers/meeting.js
api/lib/routes/meeting.js
api/package.json
api/test/tests/controllers/meeting.js

This pr adds a controller for updating meeting docs. It does not include what we will need in order to update participants and topics for a meeting. It also adds in [@starryinternet/jobi](https://www.npmjs.com/package/@starryinternet/jobihttps://www.npmjs.com/package/@starryinternet/jobi) a custom logging utility. This allows for better logging by using different logging levels. For example, we can have verbose logs what we use for debugging like this:
```js
const logger = require("@starryinternet/jobi");
logger.log( "info", "Some Message" );
```
This log will only show up when you set the `NODE_DEBUG=trace` variable when running the api. The reason we don't just go for `console.log` everywhere is that this would lead to an inordinate amount of logs in production making them difficult to …

Meeting Update Controller and Jobi Logging

---

www/components/Nav.js
www/pages/_app.js
www/pages/login.js
www/pages/register.js
www/store/store.js

Updated `register` and `login` components to use the provided `store` prop that now utilizes React's `useMemo` method that *memoizes* the state such that even when the `_app` component re-renders the state of the app persists. The implimentation can be seen in the `store.js` file.

Memoize App State

---

api/lib/controllers/user.js
api/lib/middleware/authenticate.js
api/lib/routes/index.js
api/lib/routes/meeting.js

Added authentication to restricted routes (for now those other then `/user`).
In each of the routes that we do not want to allow users to access without logging in, the `authenticate()` middleware function was added. This function parses and verifies the JWT in a requests `authorization` header. Our frontend requests will need to include an authorization header going forward.

Add authentication to restricted routes in api.

---

api/lib/controllers/user.js
api/lib/db/index.js
api/test/tests/controllers/meeting.js
api/test/tests/controllers/participant.js
api/test/tests/controllers/topic.js
api/test/tests/controllers/user.js
api/test/utils/client.js
api/test/utils/db.js

Since we added the authentication middleware to our meetings, participants, and topics [here](https://github.com/SocexSolutions/agenda-v2/blob/master/api/lib/routes/index.js#L12-L14), we need to add the `Authorization` header to each request that has an auth token as a value so that it can be verified [here](https://github.com/SocexSolutions/agenda-v2/blob/master/api/lib/middleware/authenticate.js#L13-L25).
In order to add a `Authorization` header with a token, we first need to get a token. We get a token by making a request to `user/register` with a `username`, `email`, and `password` in its payload. Then in the `before` block of the tests, we add tell `axios` to use the token as the `Authorization` header. So we end up with this before our tests:
```js
before( async() => {
await …
```

Added 'Authorization' header to test client.

---

api/lib/db/index.js

Since we upgraded `mongoose` to version 6,  most of the common connection props are now defaults meaning we no longer need to include them according to the migration docs [here](https://mongoosejs.com/docs/migrating_to_6.html#no-more-deprecation-warning-options) so we are dropping them.
Removed unnecessary connection constructor props.

Remove props in mongoose constructor.

---

.gitignore
package.json

Code coverage refers to the percentage of code in a repo that tests utilize. If tests don't utilize code, the code is considered un covered. `nyc` is a great tool for code coverage and integrated easily with `mocha` so we can use it here. We actually have code coverage currently at 89% in the api but it should at least be at 100%, ideally with multiple test cases for each line.
- Added new `coverage` script
- Installed `nyc`

add nyc for code coverage

---

www/pages/_app.js
www/store/client.js

I did a bit of work with cookie parsing stuff but this was the coolest part. Axios (our http client) allows you do add interceptors (its the middleware pattern) where you can modify requests and responses. Here we add an interceptor that parses the `document.cookie` with a new `parseCookie` util I made (an improvement over our previous implementation) and if there is an auth token, adds it to the `authorization` header of the request.

Add authorization interceptor to client.

---

api/lib/middleware/req-logger.js
api/lib/routes/index.js
api/test/tests/middlware/req-logger.js

We have a lot of copy pasta for request logging this will eliminate the need a lot of it. When running the app with `NODE_DEBUG=debug`, the requests url path will be logged as well as its body and params. With `NODE_DEBUG=trace`, the entire request object will be logged. The lowest level, `NODE_DEBUG=info`, will only show the request url path. Without `NODE_DEBUG` nothing will be logged.

Request Logging Utility

---

www/components/Bundles/Meeting/HeaderForm.js
www/components/Bundles/Meeting/ParticipantsForm.js
www/components/Bundles/Meeting/TopicsForm.js
www/components/Button.js
www/components/ChipForm.js
www/components/DropDown.js
www/components/Nav.js
www/pages/index.js
www/pages/login.js
www/pages/meeting/[id]/index.js
www/pages/register.js
www/store/client.js
www/store/features/ui/uiSlice.js
www/store/features/user/userSlice.js
www/styles/Bundles/Meeting/HeaderForm.module.css
www/styles/Bundles/Meeting/ParticipantsForm.module.css
www/styles/Bundles/Meeting/TopicsForm.module.css
www/styles/Button.module.css
www/styles/Chip.module.css
www/styles/ChipForm.module.css
www/styles/Drawer.module.css
www/styles/LoadingIcon.module.css
www/styles/MeetingPage.module.css
www/styles/Nav.module.css
www/styles/Register.module.css

Cookies are sent with requests automatically which exposes us to cross site request forgery attacks that would allow attackers to steal our users jwts thus gaining access to all their permission's until the jwt expires. Session storage is also much less exposes to cross site scripting and easier to work with so its pretty much all wins here.
Switch from `document.cookie` api to `window.sessionStorage` api for storage of our jwts. I also made a few ui changes but nothing significant.

Switch from cookies to session storage

---

api/lib/controllers/meeting.js
www/pages/user/[id]/index.js
www/store/features/meetings/meetingSlice.js

- Meetings were failing to save with owner ID's this whole time. Crazy that we never noticed this. Also strange it was still succeeding at all even with owner ID being a required field.
- Inbox page would load indefinitely if user had no meetings. Changed the way we check for meetings
- Fixed typo
- Changed the way we check for meetings on the Inbox page. If .length returned 0 page would not load.
```   ,------.
`-____-'        ,-----------.
,i--i.         |           |
/ @  @ \       /  HEE HEE!  |
| -.__.- | ___-'             J
\.    ,/ """"""""""""""""""'
,\""""/.
,'  `--'  `.
(_,i'    `i._)
|      |
|  ,.  |
| |  | |      -bodom-
`-'  `-'
```

Fix: Meetings not saving with owner ID

---

api/lib/controllers/topic.js
api/lib/models/topic.js
api/lib/routes/topic.js
api/test/fakes/topic.js
api/test/tests/controllers/topic.js

[Topic Status Prop Ticket](https://www.notion.so/thomashudsonnotes/Topic-Status-Prop-API-7ef6a765bd4a4c6ea40890c39c6a2517)
[Topic Description Prop Ticket](https://www.notion.so/thomashudsonnotes/Topic-Description-Prop-Update-API-fe0c6f030b794ac68d8b3017078408ca)
We recently decided that topic's should have `description`s and that we needed a `status` prop to persist meeting state while the meeting is ongoing. This PR adds these features.
- Added `description` and `status` properties to the `Topic` schema
- Added `update` api for topics
- Added `status` api for topics (we use a separate route to allow for different permissions)

Topic description, status, and relevant API

---

www/components/ChipForm.js

[Ticket](https://www.notion.so/thomashudsonnotes/Alert-Users-When-Duplicate-Participants-cce9343ad8a644e6a6916fe172e6f89a)
The old version of the `ChipForm` allowed elements with a duplicate `key` which caused problems due to our implementation. This PR modifies the `ChipForm` to not allow duplicates.
We currently don't have a good way to show an error in a specific input so I decided to just use `window.alert` for now and add a ticket for it.

Prevent Duplicates in ChipForm

---

www/pages/meeting/[id]/index.js
www/pages/meeting/[id]/meet.js
www/pages/meeting/[id]/voting.js
www/store/features/theme/themeSlice.js

We had previously been experiencing an issue where hard reloads caused an error in the `useEffect` hook of pages that required a db request. This error was due to the `next/router` instance not being instantiated by the time it was referenced. 
We can avoid this issue by checking if what we need from the `router` is functioning before making the request, and adding the router as a dependency to the `useEffect`. This way we perform no action before the `router` has loaded. We then detect when the `router` has loaded as it is a dependency of the useEffect and finally perform the request that relies on the router.

Fixed Hard Reload Issue

---

www/components/Bundles/Meeting/TopicsForm.js
www/components/ChipForm.js
www/pages/meeting/[id]/index.js

React uses the `key` prop to keep track of elements in an array. If the key prop does not change for an element it does not re-render the element which saves some cycles. However, when multiple elements have the same key prop and one is updated, React will use the first previously rendered version with the same key which is often inaccurate. This caused issues for us with the `TopicForm` and `ChipForm` which we can fix by not allowing duplicate `Topic` names or `Chip` names.
Don't allow duplicate keys in `ChipForm` or `TopicForm`.
We probably want to use the new `Input` notification system instead once that gets merged in.

Duplicate Key Issues

---

www/components/Input.js
www/styles/Input.module.css

Inputs on the page need to be highlighted when there is an error passed in as a prop for better visibility.
Highlight the Input component in `--danger` if the user makes an error.

added errorMessage prop to Input component

---

api/lib/controllers/meeting.js
api/lib/controllers/takeaway.js
api/lib/controllers/topic.js
api/lib/models/topic.js
api/test/fakes/topic.js
api/test/tests/controllers/meeting.js
api/test/tests/controllers/takeway.js
api/test/tests/controllers/topic.js

We want to use the `owner_id` associated with objects for our permissions system. In order to do this, we will need to make sure that the `owner_id` is present on the `meeting`, `takeaway`, and `topic` models. We also don’t want to trust that a payload has the correct `owner_id` within it. Instead we can use the `sub` (stands for subject) prop present on our JWTs which is the `user._id`.  When we have participant authentication setup this property will be the `participant._id.`
- Our create methods were already taking in a user ID from the request body (except topics). I switched this to pulling it from the request credentials.
- Added owner_id to topic faker
- Adjusted `saveMeetingTopics` to take in an `owner_id`
- [Notion](https://www.notion.so/thomashudsonnotes/Utilize-owner_id-for-obje …

Utilize owner_id for objects

---

api/lib/controllers/takeaway.js
api/lib/models/takeaway.js
api/lib/routes/takeaway.js
api/test/fakes/meeting.js
api/test/fakes/takeaway.js
api/test/fakes/topic.js
api/test/tests/controllers/meeting.js
api/test/tests/controllers/participant.js
api/test/tests/controllers/takeway.js
api/test/tests/controllers/ui.js
api/test/tests/controllers/user.js
api/test/tests/models/topic.js

Another part of the permissions epic, owner challenges for takeaways.
Added a takeaway `update` route, owner checks for `update` and `delete`, and removed `faker` since it was [unleashing the Zalgo](https://bluepnume.medium.com/intentionally-unleashing-zalgo-with-promises-ab3f63ead2fd) which caused tests to be indeterminate.

Add takeaway update and takeaway permissions.

---

www/pages/user/[id]/index.js
www/store/features/meetings/meetingSlice.js

We decided to move away from caching user meetings in the store because they will need to be refreshed regularly anyway.
Use the `client` to fetch meetings.

Don't use store for user meetings.

---

www/pages/meeting/[id]/index.js

When creating a new meeting. Page would not reroute you to the created meeting. 
If a new meeting is being created then reroute to new meeting edit page after save
This implementation might be a little confusing for the user. Maybe we could add a back to inbox prompt?

New Meeting Reroute

---

api/lib/auth/check-participant.js
api/lib/controllers/meeting.js
api/lib/controllers/takeaway.js
api/lib/controllers/topic.js
api/lib/controllers/ui.js
api/lib/controllers/user.js
api/lib/middleware/authenticate.js
api/test/fakes/user.js
api/test/tests/auth/check-participant.js
api/test/tests/controllers/takeway.js
api/test/tests/controllers/topic.js
package.json

This is just another step toward authorization for all of our API routes.
I modified the `check_participant` authorization utility to return an object containing `authorized` and the `meeting` that was checked against. This allows us not to duplicate requests for the same meeting. Additionally, the `authenticate` middleware now adds the `user` to `req.credentials` since we end up needing the `user.email` in the vast majority of scenarios. 
We might be able to move away from doing this if we switch away from participants containing the user's email and instead containing a `user._id`. This would make meeting creation more difficult since we might need to create non-registered users. I am still figuring out how that would work.

improved check_participant auth util

---

api/lib/models/participant.js
api/lib/models/takeaway.js
api/lib/models/topic.js

Need indexes on frequently used query params
Refs:
[Best Practices](https://www.mongodb.com/blog/post/performance-best-practices-indexing)
[Mongoose doc](https://mongoosejs.com/docs/guide.html#indexes)
[MongoDB doc](https://www.mongodb.com/docs/manual/indexes/) (for index options)
Mongoose makes indexing easy. Just add `index: true` to the whatever schema field you want the index on and it will automatically create an index for that field.

Indexes on meeting_id Field Level

---

www/pages/meeting/[id]/meet.js

If a meeting has no topics, the page would be stuck in an infinite cycle of loading. **We will want to handle meetings with no topics somehow when the owners goes to start the meeting. Like a prompt "Are you sure you want to start the meeting with no topics?" or maybe disallow it altogether.** 
Checking topic array length to display loading bar was breaking it. We already had topic loading state so I just used that instead.

No Topics Bug

---

api/lib/controllers/takeaway.js
api/lib/models/takeaway.js
api/test/fakes/takeaway.js
api/test/tests/controllers/takeway.js
www/pages/meeting/[id]/meet.js

Adding the meeting id to takeaways will make authorization simpler because we will not need to fetch the takeaway's related topic in order to get the meeting id which we need to check if the user is participant of a meeting.

feat(takeaways): add meeting._id to takeaways

---

www/api/client.js

I messed up the origin for the client originally. At least until we are rolling in dough we will be at meetingminder.dev.

fix(www:client): make sure client origin is correct

---

.github/workflows/pr-test.yml
api/lib/controllers/meeting.js
api/test/tests/controllers/meeting.js

I was thinking about how checking off action items should actually work and realized that we might just want a meeting review page that reads more like well organized meeting notes. We will need everything for the meeting review page so this controller seems like the best way to do it.
Note: make sure that your local mongo is running version 6, otherwise the nested joins in this query will not work.

feat(api): add support for takeaways and action items in meeting agg

---

docker-compose.yaml
scripts/dev.sh

Docker [image]:latest tag does not actually pull latest image version
https://cloud.ibm.com/docs/Registry?topic=Registry-troubleshoot-docker-latest
Tagged at mongo 6.0

Tagged mongodb version

---

www/classes/meeting-api.js
www/classes/rest-api.js
www/classes/topic-api.js
www/components/Layout/Nav/Nav.js
www/components/shared/ChipForm/ChipForm.js
www/components/shared/ChipForm/ChipForm.module.css
www/pages/meeting/[id]/edit.js
www/store/features/meeting.js
www/store/features/participant.js
www/store/features/topic.js
www/store/root.js
www/store/utils/slice-generator.js
www/styles/pages/meeting/[id]/edit.module.scss

There are only three places where we aren't yet using the new store, the meeting index page (which might never use the store), the meeting edit form, and the chip form. This pr modifies the meeting edit page to use the store as well as fixing the errors that would history button errors.
**Meeting Form**
Because we want the edit meeting page to be responsive, it needs to maintain it's own state (it cannot afford to wait for an update request). However, we also want it to use a cached meeting if one exists to avoid any loading time. To accomplish this, I grab the existing meeting from the store if it exists using a selector and then use it to set the meeting forms state. A request to fetch the meeting is dispatched regardless of if it was cached so that any discrepancies are immediately …

Make Meeting Edit Use Store and Fix History Button Errors

---

www/classes/rest-api.js
www/components/pages/Edit/HeaderForm/HeaderForm.js
www/components/pages/Meet/ActionItemBoard/ActionItemBoard.js
www/components/pages/Meet/TakeawayBoard/TakeawayBoard.js
www/components/shared/CardBoard/CardBoard.js
www/components/shared/ChipForm/ChipForm.js
www/hooks/use-debounce.js
www/pages/login.js
www/pages/meeting/[id]/edit.js
www/pages/meeting/[id]/meet.js
www/pages/register.js
www/store/features/topic.js
www/store/utils/slice-generator.js
www/styles/pages/register.module.css

After playing around with the updated version of the store I noticed that there were unexpected delays in requests which made things slightly less snappy. You couldn't really notice them before because there was a lot more load times. However, with the new store a lot of stuff gets cached which means that the vast majority of actions now take less than 50ms so the extra debounce delay was bothersome. We only really need to debounce text inputs that send real time updates which is only relevant for the meeting edit page and register page so I removed debounce from clients and added a new debounce hook.
I also moved the state management of the `HeaderForm` to the component since it isn't really related to the page and the page can just subscript to the store.

fix(www): rm unecessary debounces

---

api/lib/controllers/pubkey.js
api/lib/controllers/user.js
api/lib/routes/index.js
api/lib/routes/pubkey.js
api/test/tests/controllers/action-item.test.js
api/test/tests/controllers/meeting.test.js
api/test/tests/controllers/participant.test.js
api/test/tests/controllers/pubkey.test.js
api/test/tests/controllers/takeway.test.js
api/test/tests/controllers/topic.test.js
api/test/tests/controllers/ui.test.js
api/test/tests/controllers/user.test.js
www/api/client.js
www/pages/api/[...slug].js
www/store/features/user.js

I'm not entirely sure how this wasn't noticed yet but the current CORS setup doesn't allow requests from `www.meetingminder.dev` only `meetingminder.dev` (the exact origin of the api). To resolve this, I am modifying the client to always hit the web server which will proxy requests to meetingminder.dev. If you are wondering why we don't just add another item to the CORS allowed origins, the main reason is that by using the proxy setup we can use the native cookies in the browser and just convert the cookies to bearer tokens at the proxy. This makes the axios configuration much simpler while still maintaining a single auth strategy for the api.

Fix Cors and Make Auth Response Meet RFC6749

---

www/components/shared/ChipForm/ChipForm.js
www/pages/meeting/[id]/edit.js

We weren't really doing any kind of validation of participant emails. This PR adds a validate function as a prop to the ChipForm as well as a validateMsg. When the validate function returns false for an itemKey, it will display the error message on the input. It is a bit nicer then the big bottom error banner because it draws the user to the problem in the form.

feat(www:Edit): validate participant emails

---

www/components/Layout/Nav/Nav.js
www/store/features/user.js

We originally used the token in the store to give to the client and to determine if a user had authenticated. However, we are just using a cookie that axios automatically uses now so we can make things more secure by not storing the token anywhere else.

fix(store): remove token references from user store

---

api/lib/models/meeting.js
api/lib/models/participant.js
api/lib/models/user.js

While reviewing for my interview I read through MongoDb's docs on indexes and noticed that there are a few places where we should have indexes but we don't. This pr adds those indexes.
- Added a descending index on meeting date since we sort by meeting date by default.
- Added indexes to the `email` field of the participant and user models since we use them in the join for the inbox query.

Indexes for Inbox Query

---

www/components/Layout/Nav/Nav.js
www/pages/_app.js
www/pages/api/[...slug].js
www/store/features/user.js

Another realization while prepping for the interview. Since we now just use cookies and proxy requests through the web server, it is trivial to use `HttpOnly` cookies which make cross site scripting even more difficult (you can't access them with js in the browser).

HttpOnly SameSite Cookies & Fix Logo Ref

---

.github/ISSUE_TEMPLATE/bug.yml
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
pull_request_template.md

Added community documents both for our own reference and for the reference of outside contributors
- Issue remplate - https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
- PR template - https://github.com/axolo-co/pull_request_template
- Code of conduct - https://www.contributor-covenant.org/
- Contributing - written by me

Added Community Documents

---

www/components/Layout/Nav/Nav.js

The back button lets you go back to before you logged in which is weird. Now it doesn't do that.

feat(www): disable back button if leaving app

---

api/lib/controllers/user.js
api/test/tests/controllers/user.test.js
www/pages/api/[...slug].js

I modified the register method to use `access_token` as apposed to `token` in the authentication payload since that is what is recommended in the spec. Looks like I didn't do that for the login route and our tests didn't catch anything not working. I added some new tests to validate the jwt being returned which should make this less likely in the future. Obviously an E2E test would be better but I'm not sure how we want to do that.

Use access_token in authentication response payload

---

www/components/pages/Home/Inbox/Inbox.module.scss
www/components/pages/Home/Inbox/InboxRow/InboxRow.js

When a meeting has no name it doesn't have a clickable box used to open it. This PR modifies the inbox to provide a default so that all meetings can be selected and also makes the box larger so that they are easier to click.
**Current Behavior:**
https://user-images.githubusercontent.com/54583311/206508244-d7af9744-142a-4c4f-aeb5-13cd83728f0b.mov
**New Behavior:**
https://user-images.githubusercontent.com/54583311/206508647-0997e6db-caeb-4307-b953-0e5b14444cba.mov

fix(www:inbox): default meeting name

---

www/components/Layout/Drawer/Drawer.module.scss

The drawer is currently a little bit weird in that when it collapses the action item button momentarily displays as two lines before disappearing. This pr fixes the issue by adding a minimum width for the button. To make the drawer seem more natural, I also added a translation so that the buttons move in the direction that the drawer is being closed.
**Current Behavior:**
https://user-images.githubusercontent.com/54583311/206501552-c189be15-7308-4be6-9b15-75900be82af7.mov
**New Behavior:**
https://user-images.githubusercontent.com/54583311/206501632-b9f83ce3-9b94-4ba0-82f8-bfdb8f2baefe.mov

fix(www:drawer): no button text wrapping

---

www/components/pages/Edit/TopicBoard/TopicBoard.js
www/components/pages/Edit/TopicBoard/TopicBoard.module.scss
www/components/shared/TopicCard/TopicCard.js
www/components/shared/TopicCard/TopicCard.module.scss
www/pages/meeting/[id]/edit.js
www/styles/globals.css

This pr modifies the meeting edit page so that it doesn't create new empty topics each time that the user clicks add topic. Instead, the topic state is stored locally and is identified with an id prefixed with `temp`. I also added a new `TopicCard` component specific to topics that has a unique topic icon. This should make it easy for the user to differentiate between each type of item.
**Preview:**
https://user-images.githubusercontent.com/54583311/206785745-1d624a7c-e958-4688-94bd-9d74df6b7cac.mov
Just did some simple manual test to check that crud operations on topics still work.

feat(www:edit): refactor edit page to use new temp id pattern

---

www/pages/user/[id]/home.js

The create button on the home page fades in and out when the table is reloaded which doesn't make sense. This pr prevents that behavior.
https://user-images.githubusercontent.com/54583311/212727798-0b4e0ce1-0fb9-40dd-8641-6924212ffeb2.mov
https://user-images.githubusercontent.com/54583311/212728000-dfb89e53-eaf1-4897-9bee-2cfda9063fca.mov
Just tested that the create fab still works as intended and that it remains visible through the process of loading new meetings.

Fix Create Fab Fade
