SocexSolutions/agenda-v2

www/components/Nav.js
www/pages/register.js

This is more of an example then a final product but this should be sufficient for you guys to work off of. 
This PR has a `Register` page that uses a **pre-created action** from the `store/features/user/userSlice.js` file called `userRegister`. This **action** then makes an asynchronous call to the API to authenticate a user and get a JWT.
The action adds the JWT to the user portion or **slice** of our **store** object as well as other user data. The `nav` component is **subscribed** to changes in the store using the `useSelector` hook and the `selectUser` **selector** defined in the component. 
When the API reply is received, the store changes and because it is subscribed, the `Nav` component re-renders with the `user.username` as an `<h1>`. When going to different pages, the `Nav` …

User Register Page

---

www/components/Chip.js
www/styles/Chip.module.css

Added a chip component, wasn't really sure how to add the icons to it so I decided to leave it out for now.

Added Chip Component

---

www/components/Input.js
www/pages/register.js
www/styles/Button.module.css
www/styles/Register.module.css

Added in the register page styles. It would be super cool if we could overwrite some of the button and input styles so I can get it just right. 
@zbarnz I have a few requests:
- Do you think you could make it so that we can add our own classes to them that overwrite properties when we need to?
- Can you make it so that the `secondary` button variant has no background color? 
- Can you make it so that the background color doesn't change when you start typing in an input?

Register Page Styles

---

api/.gitignore
api/lib/utils/keygen.js
www/components/LoadingIcon.js
www/styles/LoadingIcon.module.css

#Preview 
#Features
Change the size. Small, medium, and large

Loading Screen Icon

---

www/components/Button.js
www/components/Drawer.js
www/components/Layout.js
www/styles/Button.module.css
www/styles/Drawer.module.css
www/styles/Layout.module.css

I added the drawer prototype to the `Layout` but I think we probably just want to keep it in the component. I am too tired to think about it right now. Either way it looks pretty great, thanks @zbarnz for the styles! I think we just need to add a container for the icon in that doesn't break other buttons and these should be just about perfect.

Drawer Prototype

---

api/lib/controllers/meeting.js
api/lib/db/index.js
api/test/tests/controllers/meetin.js

MY FIRST TEST WOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

---

api/lib/controllers/user.js
api/lib/routes/health.js
api/test/tests/controllers/health.js
api/test/tests/controllers/participant.js
api/test/tests/controllers/user.js

Refactored the User, Participant, and Health tests to use `axios` for making requests instead of the custom module that I created. If the `mongo` container is running the tests can be run from the `/api` directory with `npm run test`.

Refactor Tests

---

api/lib/controllers/meeting.js
api/lib/models/meeting.js
api/lib/models/participant.js
api/test/tests/controllers/meeting.js
api/test/utils/client.js

This PR fixes the meetings tests so that they are more precise and adds in an `client.js` file that can be used by for our API tests. This way when we make a change to the URL or add in authorization we can change it in one place as well.
- Added `client.js`
- `meetin.js` => `meeting.js`
- Refactored `meeting` tests with `client`, added better error messages, and checked that the *right* error actually occurs when we want one to

Added Client and Improved Meeting Test Specificity and Sensitivity

---

www/components/AgendaIcon.js
www/components/Nav.js
www/styles/AgendaIcon.module.css
www/styles/Nav.module.css

I made an AgendaIcon component to look like the figma design by using an empty calendar icon with a checkmark alarm icon positioned within.  I added this to the navbar by agenda
I fixed the positioning by moving agenda over from the left in the nav bar and moving the login/signup over to the right by the same amount.  Now this looks more like the figma design.

fixed nav bar positioning and added agenda icon

---

api/lib/controllers/topic.js
api/lib/models/topic.js
api/test/tests/controllers/topic.js

Added topic API tests as well as modified the controller to send back the Topic. We send back the topic so that we can validate that it was created correctly.
One potential issue is keeping track of who can delete topics. We may want to add in a `topic_owner` attribute at some point that is either a reference to a `participant` or a `user`. I don't think that we should allow editing topics as a user could add a popular topic get some likes on it then change it to something less popular manipulating the system.

Topic API Tests

---

api/lib/db/index.js
www/components/Input.js

Working with environment variables is a great way to configure different aspects of your Node.js application. Many cloud hosts (Heroku, Azure, AWS, now.sh, etc.) and Node.js modules use environment variables. Hosts, for example, will set a PORT variable that specifies on which port the server should listen to properly work. Modules might have different behaviors (like logging) depending on the value of NODE_ENV variable.
Here are some of my tricks and tools when working with environment variables in Node.js.

Added NODE_ENV options

---

api/lib/db/index.js
www/pages/login.js
www/store/features/user/userSlice.js
www/styles/Layout.module.css
www/styles/Register.module.css

This PR is for when I meet with Tom.

Login Page

---

api/.eslintrc
api/lib/controllers/meeting.js
api/lib/controllers/participant.js
api/lib/routes/meeting.js
api/lib/routes/participant.js
api/test/tests/controllers/meeting.js
docker-compose.yaml

This PR modifies the `display` controller with the route `meeting/:_id` to also find related `participants`. Will be adding in the lookup for `topics` next.

Display meeting route now looks up participants.

---

api/lib/controllers/meeting.js
api/lib/routes/meeting.js
api/test/tests/controllers/meeting.js
api/test/utils/api.js
api/test/utils/client.js
api/test/utils/db.js

Added index route to show all meetings as well as controller integration tests. Also fixed the `clean()` database utility for tests which delete all data in the `agenda-test` database in mongo.

Created index route and test for meetings.

---

www/components/Button.js
www/components/Nav.js

Fixed button text default so that the nav bar is not messed up 
also added username in to show while user signed in

fixed the darn default text

---

api/lib/controllers/user.js
www/pages/meeting.js

Added in meeting form methods to be passed to child components.
Co-authored-by: zbarnz <zbarnz@yahoo.com>
Co-authored-by: dahvd <davidoligney@gmail.com>

Meeting form methods.

---

scripts/dev.sh

The `dev.sh` script has been updated so that it now captures the child process ids spawned from the script and waits on both of them to be completed. What this means is that the when a termination request is made with `ctrl+c` the script will communicate this request to the processes it is waiting on. In this case, the frontend Next.js server and the backend docker containers for the API and MongoDB.
- Capture child process id's in `dev.sh` script and wait on them.

Updated dev.sh to wait on both the frontend and backend processes.

---

api/lib/controllers/user.js
www/components/Attendies.js
www/components/MeetingNameDate.js
www/components/MeetingTopics.js
www/pages/meeting.js
www/styles/MeetingTopics.module.css

Meeting form logic.
Zach did everything here
Co-authored-by: zbarnz <zbarnz@yahoo.com>

Meeting Logic

---

api/lib/controllers/meeting.js
api/lib/controllers/user.js
api/lib/models/meeting.js
api/lib/models/topic.js
api/lib/routes/topic.js
api/test/tests/controllers/health.js
api/test/tests/controllers/meeting.js
api/test/tests/controllers/participant.js
api/test/tests/controllers/topic.js
api/test/tests/controllers/user.js
package.json

Updated tests still using axios to use custom client. Modified meeting model, controller, and tests to accomodate name attribute. Modified controllers not matching rest specs to meet the standard. Updated the test script in the home directory to run the scrip with NODE_ENV=test which updates the api port to 4000 (allowing tests to be run while app is running).
- You can now use `npm run test` to run the tests while the app is running
- Our meeting controller is ready to go

Meeting Topic Aggregation and Test Updates

---

www/components/MeetingParticipants.js
www/components/MeetingTopics.js
www/pages/meeting.js

Updated the participants and topics to use a set instead of an array. Sets don't allow for duplicates which makes our job quite a bit easier and the app ever so slightly more performant.

Switch to Sets for Participants and Topics

---

api/lib/utils/autoPopulate.js
scripts/dev.sh

Script for better dev ergonomics that pre-populates the database.
Co-authored-by zbarnz <zbarnz@yahoo.com>
Co-authored-by Dahvd <davidoligney@gmail.com>

Database Population Script

---

api/lib/routes/meetingSave.js
www/components/Nav.js
www/pages/meeting.js
www/store/features/meetings/meetingSlice.js
www/store/features/user/userSlice.js

Added reducer for saving meetings. It will use the api route.
Co-Authored-By: zbarnz <zbarnz@yahoo.com>

Added reducer for creating meetings

---

api/lib/controllers/meeting.js
api/lib/db/index.js
api/lib/index.js
api/test/tests/controllers/meeting.js
api/test/tests/controllers/participant.js
api/test/tests/controllers/topic.js

Updated the POST route at `/meeting` to take in the meeting info, topics, and participants and perform a transaction to safely create or update them in the database.

Save Meeting Api Route

---

www/components/Notification.js
www/styles/Notification.module.css
www/styles/globals.css

A notification component that you can pass text into

Notification Popout

---

api/lib/controllers/meeting.js
api/lib/controllers/participant.js
api/lib/controllers/topic.js
api/lib/db/index.js

I noticed that when we are debugging, we often end up putting the same logs in the same places to determine the issue. In order to reduce this repetition, I added in some more logs. Logs are done with `jobi` and `logger.debug` which is handy because they will only be visible when `NODE_DEBUG=debug` is set which is set in the new `docker-compose`.
- Add logs to controllers with the route name, `req.body`, and `res.payload`.

Added additional logging to make debugging easier later on.

---

README.md
api/Dockerfile
api/lib/index.js
api/test/utils/http.js
docker-compose.yaml
www/store/client.js

Did it again Uber Fast

---

www/components/Input.js
www/components/Nav.js
www/styles/LogReg.module.css

Resolved Ticket: [Fix Minor CSS Issues](https://thomashudsonnotes.notion.site/Fix-Minor-CSS-Issues-896fe4f977964d318f382dd2b3f0facf) 
Changed placeholder color and removed outline when selected.

made input pretty

---

.github/dependabot.yml
api/package.json
package.json
www/package.json

Co-authored-by: zbarnz <zbarnz@yahoo.com>
Co-authored-by: dahvd <davidoligney@gmail.com>
You should have been here.

Add support for workspaces.

---

www/components/DropDown.js
www/components/Nav.js
www/pages/user/[id]/index.js
www/store/features/user/userSlice.js

I hooked up the existing dropdown menu to your username in the corner, we can now logout which is a little useful.
When you click you username in the corner you are now presented with a menu rather than being redirected to your inbox. The only functional button in the dropdown is the logout button. We will have to discuss what else we want in this menu as the rest are just placeholders.

Added DropDown w/ Logout

---

.github/workflows/pr-test.yml
package.json
scripts/keygen.js
www/pages/meeting.js

Github makes it pretty easy to automatically run tests when a PR is made, this workflow runs the mocha tests for our backend and will give us a green checkmark if they pass and notify is if they fail.
The only thing required for this is to add the `.github/workflows/{some-work-flow}.yml` file.

Add pr-test.yml workflow.

---

www/components/Drawer.js
www/styles/Drawer.module.css

ARROW NOW STICKES OUT OF DRAWER - $1 (Littleton)

changed drawer arrow look

---

api/lib/controllers/meeting.js
api/lib/controllers/participant.js
api/lib/controllers/topic.js
api/lib/controllers/user.js
api/lib/middleware/req-logger.js
api/test/tests/middlware/req-logger.js
api/test/utils/api.js

Added an interceptor to the `res.send()` method that will log responses.

Added res.send() interceptor to log responses

---

api/lib/controllers/meeting.js
api/lib/controllers/user.js
api/test/tests/controllers/user.js
api/test/tests/middlware/authenticate.js
package.json

I'm pushing for 100% test coverage on the backend. This pr improves some of the user routes and adds tests for the `refresh` resource and `authenticate` middleware and gets us to 94.75%.
- Added tests for `*/user/refresh`
- Added test for `authenticate` error handling
- Modified `package.json` to only account for coverage of `api/lib`
*Note: The `*/user/save` route/resource got messed up in the previous pr so I have restored it here.*

Increase test coverage and improve user resources

---

www/components/Snackbar.js
www/pages/_app.js
www/pages/login.js
www/pages/meeting/[id]/index.js
www/pages/user/[id]/index.js
www/store/features/meetings/meetingSlice.js
www/store/features/user/userSlice.js

Co-authored-by: Zbarnz <zbarnz@yahoo.com>

Global snackbar with async functionality

---

api/lib/controllers/user.js
api/lib/routes/user.js

Checks if username and email exist when user is registering in real time.
Added a function that makes a request to the database on every keystroke. The form messages will need styled but wanted to submit this for review before because I'm procrastinating.
═══════════════════░▒░══════════════════
════════════▒▒▒▓███████████▓▒═══════════
════════▒██████████▓▓▓▓██▓████▓═════════
══════▒███████▓█▓▓▓█▓█▓███▓▓▓███════════
═════▓███▓██▓▓████▓██▓█▓▓▓███▓██▒═══════
═════▓██▓███▓█▓████████▓▓█████▓██═══════
═════▒█████████▓▓▓███████████████▒══════
═════▒██████▓█████▒▒▒▒▒██████████▒══════
═════▒███████▓█▓█▒═════░▒▓█▓▓▒▒██▒══════
═════▒█████████▓█▓░░▒▒░░░░░▒▒▒▒██▒══════
═════▒████████████▒░▒▒▒▒▒▒▒▒▒▒▒▓█▒══════
═════▒██████████▓▓▓▒▒▒▒▒▒▒▒▒▒▒░▓█▒══════
═════▒███████▓███▓▒▒▒▒▒▒▒▒▒▒▒▒░▒▓▒══════ …

Form Validation

---

www/styles/Inbox.module.css

- Inbox UI looked a little ug to me
- added container

added meetings container

---

api/lib/controllers/ui.js
api/lib/models/ui.js
api/lib/routes/index.js
api/lib/routes/ui.js
api/test/fakes/theme.js
api/test/tests/controllers/ui.js
www/components/Drawer.js
www/components/DropDown.js
www/components/Layout.js
www/components/Nav.js
www/components/Snackbar.js
www/pages/_app.js
www/pages/login.js
www/pages/meeting/[id]/index.js
www/pages/meeting/[id]/meet.js
www/pages/register.js
www/pages/user/[id]/index.js
www/store/client.js
www/store/features/drawer/drawerSlice.js
www/store/features/meetings/meetingSlice.js
www/store/features/snackbar/snackbarSlice.js
www/store/features/theme/themeSlice.js
www/store/features/ui/uiSlice.js
www/store/features/user/userSlice.js
www/store/rootReducer.js
www/styles/Snackbar.module.css
www/styles/globals.css
www/utils/parseCookie.js
www/utils/theme.js
www/utils/wait.js

Added themes you know you were there. Fixed tests and everything is working as it should. Next step for this branch should be to add more themes and create some kind of modal for theme picking or something

Theme controller and UI model

---

api/lib/controllers/topic.js
api/lib/models/topic.js
api/lib/routes/topic.js
api/test/fakes/topic.js
api/test/tests/controllers/topic.js

Co-authored-by: Tom Hudson <thudson1998@hotmail.com>
```
....:::::::::....                               ....:::::::::....
..:::''''         '''':::..                     ..:::''''         '''':::..
.:''                       '':.    ..:::::..    .:''                       '':.
.:'                             ':.::''     ''::.:'                             ':.
.---::______________________________.::_____________::.______                ____....::---.
:___::_____________________________:c::_____________::z:_____`.__....----""""____....::___:
'::                            '_.:'        ____.::.:-"""":.`.....----""""        ::'
':.                        ____.::.----""""____..::.-""""  `.`.                 .:'
':.                     .'___.::..----""""        ':.       : :               .:' …
```

Added likes to topic controller + tests

---

api/test/fakes/meeting.js
api/test/fakes/participant.js
api/test/tests/controllers/meeting.js

No changes, just making the tests a little better.

Some Test Improvements

---

api/test/tests/controllers/topic.js

A while back I noticed that we were only testing the response from some `topic` operations. This pr adds check of the database after reach op.
- Use `topicFaker` for all tests
- Check db that all operations were completed successfully.

topic test improvements

---

www/components/Layout.js

drawererer doesnt show up on homepage now

fix drawerer showing up on main page

---

www/components/Input.js
www/styles/Input.module.css

Added multiline functionality to our input
Change to `<textarea>` tags when `multiLine = { true }` is passed into our input component as a prop

Multiline Input

---

www/components/Inbox.js
www/styles/Inbox.module.css

[Notion](https://www.notion.so/thomashudsonnotes/a1f3e7cd3bf74c62b06dbda78b2c9c7c?v=43d3f2b9730045f691cd254967c6949d&p=5c4e037cf38544d2933d96ba49fd83ed)

message when you have no meetings

---

www/components/Nav.js

back history button that WORKS going forward

---

api/lib/controllers/meeting.js
api/lib/routes/meeting.js
api/test/tests/controllers/meeting.js
www/components/Bundles/Meeting/TakeawayBoard.js
www/pages/meeting/[id]/meet.js
www/store/features/meetings/meetingSlice.js
www/store/features/snackbar/snackbarSlice.js
www/styles/globals.css

Ticket: [Switch Between Topics](https://www.notion.so/thomashudsonnotes/Switch-Between-Topics-3c5718085e654e378bf63317c0c9b29c)
While in a meeting, users should be able to switch between topics of discussion. This pr adds that functionality as well as the remaining plumbing needed to move away from using the store.

Switch Between Topics on Meet Page

---

www/components/Button.js
www/components/Layout.js
www/components/Nav.js
www/pages/meeting/[id]/index.js
www/pages/meeting/[id]/voting.js
www/styles/Voting.module.css

Navigation Buttons Improvements

---

www/styles/Button.module.css

changed disabled style

---

www/styles/Button.module.css

 unblundered icon button

---

www/pages/meeting/[id]/index.js

New meetings would be sending an invalid id

fixed meeting creation

---

www/components/DropDown.js
www/pages/_app.js
www/pages/register.js
www/store/features/user/userSlice.js

We were setting the route manually which which is out of scope of the state management of the router. As a result, it would not actually perform the redirect.
Switch to the use of `next/router` instead of `href` to bring the route back into the app state.

fix logout lag issue

---

www/styles/DropDown.module.css

Inbox item buttons were overlaying dropdown during transition
changed z-index of dropdown menu to 1

Inbox Bug Fix

---

api/scripts/autoPopulate.js

Handling topics is now functional enough that it makes sense to have them auto-populated on our test account.
Give each meeting 5 topics with some random `faker` name and lorem ipsum paragraph description.
Also changed the autoPopulate functions to snake case

Autopopulate Topics

---

api/lib/controllers/meeting.js
api/lib/controllers/user.js
api/lib/middleware/authenticate.js
api/lib/middleware/req-logger.js
api/lib/routes/user.js
api/lib/util/authorization.js
api/test/tests/controllers/meeting.js
api/test/tests/middleware/req-logger.js
api/test/tests/util/authorization.js

We didn't have test for these endpoints.

tests for getTopics and getParticipants

---

api/lib/db/index.js
scripts/dev.sh
www/components/Hr/Hr.js
www/package.json
www/pages/meeting/[id]/index.js
www/pages/register.js

These are some small fixes necessary for the build to succeed (and thus deployment).

Small Fixes for Build

---

api/lib/db/index.js
docker-compose.yaml
www/.dockerignore
www/.env.development
www/.env.production
www/api/client.js

[meeting minder](https://meetingminder.dev)

feat(environment): use environment variables for configuration

---

api/lib/controllers/action-item.js
api/lib/controllers/topic.js
api/lib/models/action-item.js
api/lib/routes/action-item.js
api/lib/routes/index.js
api/lib/routes/topic.js
api/test/fakes/action-item.js
api/test/tests/controllers/action-item.js
api/test/tests/controllers/takeway.js
api/test/tests/controllers/topic.js
www/api/action-item.js
www/classes/topic-api.js
www/pages/meeting/[id]/meet.js

Action Items Backend

---

api/lib/controllers/meeting.js
api/lib/routes/meeting.js
api/test/tests/controllers/meeting.js
www/components/Layout/Nav/Nav.js
www/components/pages/Home/Inbox/Inbox.js
www/components/pages/Home/Inbox/Inbox.module.scss
www/components/pages/Home/Inbox/InboxRow/InboxRow.js
www/components/pages/Home/Inbox/MeetingModal/MeetingModal.js
www/pages/user/[id]/home.js

**Description**
Adding the ability to delete meetings.
**Preview**
https://user-images.githubusercontent.com/54583311/194782892-63eafbbc-a107-4bb6-968d-fd85711dac0d.mov

Meeting Delete

---

api/lib/models/meeting.js
www/components/Layout/Layout.js
www/components/Layout/Layout.module.css
www/components/pages/Meet/ActionItemBar/ActionItemBar.js
www/components/pages/Meet/ActionItemBar/ActionItemBar.module.scss
www/components/pages/Meet/TopicDisplay/TopicDisplay.js
www/components/pages/Meet/TopicSelectBar/TopicSelectBar.js
www/components/pages/Meet/TopicSelectBar/TopicSelectBarButton/TopicSelectBarButton.js
www/components/pages/Meet/TopicSelectBar/TopicSelectBarButton/TopicSelectBarButton.module.scss
www/pages/meeting/[id]/meet.js
www/styles/pages/meeting/[id]/meet.module.scss

Added some new features to the meet page like topic completion, topic priority display, topic ordering, and closing a meeting. Also of note, CD has been setup for both the web server and api servers so when this is merged to `master` it will be immediately deployed to meetingminder.dev.
https://user-images.githubusercontent.com/54583311/200042866-26e83af7-ba3c-4fd7-b961-9c749a48de5f.mov

Meet Features

---

.github/workflows/pr-test.yml

Adding build to the CI tests as a start to testing the UI.

chore(www): add build to CI

---

docs/authentication.md

There was a typo in your authentication docs.

Fixed Typo

---

www/components/shared/CardForm/CardForm.js

I had trouble with login/backend so i couldn't check it but it should work

Make Card Inputs Automatically Adjust Size #345

---

api/test/utils/create-users.js

We have repeatedly used the same code to setup users related and unrelated to a meeting. This utility should help.

Meeting Setup Util for Testing

---

api/lib/controllers/group.js
api/lib/models/group.js
api/lib/routes/group.js
api/lib/routes/index.js
api/lib/util/authorization.js
api/test/tests/controllers/group.test.js
api/test/utils/setup-meeting.js

[Tags Proposal](https://github.com/SocexSolutions/agenda-v2/issues/318)
This PR adds the model for groups as well as the controllers for updating and creating the groups necessary for tags.
Full coverage unit tests.

Groups Init

---

api/lib/controllers/meeting.js
api/test/tests/controllers/meeting.test.js
www/components/pages/Home/Inbox/Inbox.js
www/components/pages/Home/Inbox/Inbox.module.scss
www/pages/api/[...slug].js
www/pages/user/[id]/home.js

@thudsonbu I did not think the foreground style worked well on the filters box
- Added live update on type for search
- functional owners dropdown with multiple selections possible
- Search is case insensitive and functions like SQL `LIKE` operator.
- Pages update live depending on filters
- Limit to 14 results per page hard coded. Need suggestions on this

Filters and Pagination

---

www/components/pages/Home/Inbox/MeetingModal/MeetingModal.js

Fixed check for meeting ownership when opening a model of an inbox line item. 
Fixes # (issue)
Please delete options that are not relevant.
Confirmed getting owner controls on inbox modal for owned meetings. Also confirmed non owned meetings dont get a modal.

Fix check for meeting ownership

---

api/lib/controllers/invite.js
api/lib/models/invite.js
api/lib/models/user.js
api/lib/routes/index.js
api/lib/routes/invite.js
api/test/tests/controllers/group.test.js
api/test/tests/controllers/invite.test.js

[Proposal](https://github.com/SocexSolutions/agenda-v2/issues/318)
This pr adds controllers that allow users to create invites to groups, cancel those invites, or if the user has been invited, accept them.
100% coverage unit tests.

Invite Creation, Cancellation, and Response Controllers

---

.eslintrc
.github/pull_request_template.md
.github/workflows/pr-test.yml
api/lib/middleware/req-logger.js
api/package.json
api/test/tests/models/topic.test.js
package.json
www/.eslintrc
www/package.json
www/store/features/drawer.js
www/store/features/snackbar.js

Adding the lint step to the build to validate code formatting. This involved fixing some linter config issues. I also moved the pr template to the `.github` folder and modified it so that you don't need to delete anything when you use it.
Basic unit tests.

Add Lint to Build & PR Template Tweaks

---

api/lib/controllers/meeting.js
api/lib/controllers/tag.js
api/lib/controllers/user.js
api/lib/middleware/authenticate.js
api/lib/models/meeting.js
api/lib/models/tag.js
api/lib/routes/index.js
api/lib/routes/meeting.js
api/lib/routes/tag.js
api/lib/sendgrid/sendgrid.js
api/lib/util/authorization.js
api/test/fakes/group.js
api/test/fakes/register.js
api/test/fakes/tag.js
api/test/fakes/user.js
api/test/tests/controllers/group.test.js
api/test/tests/controllers/invite.test.js
api/test/tests/controllers/meeting.test.js
api/test/tests/controllers/tag.test.js
api/test/tests/controllers/user.test.js
api/test/tests/middleware/authenticate.test.js
api/test/tests/util/authorization.test.js
www/pages/meeting/[id]/edit.js
www/utils/muiTheme.js

[Proposal](https://github.com/SocexSolutions/agenda-v2/issues/318)
This pr adds support for creating tags as well as various refactorings that improve the quality of our tests.
Please delete options that are not relevant.
Full coverage unit tests.

Tags Model & Creation | Improve Authorization Utils and Tests | Add Groups in User Controller Responses

---

.github/workflows/pr-test.yml
api/lib/controllers/meeting.js
api/lib/controllers/user.js
api/lib/models/topic.js
api/lib/routes/user.js
api/lib/util/mutex-lock.js
api/test/tests/controllers/meeting.test.js
api/test/tests/controllers/user.test.js
scripts/dev.sh
scripts/push-api-to-gcr.sh
scripts/push-www-to-gcr.sh
scripts/setup.sh
scripts/test.sh

This PR adds an endpoint for fetching all of a user's related groups and makes the last few changes to get our API to 100% test coverage 🎉.
100% coverage unit tests ✅!

Groups Aggregate & Test Coverage

---

api/lib/controllers/meeting.js
api/lib/controllers/topic.js
api/lib/routes/meeting.js
api/lib/routes/topic.js
api/test/tests/controllers/meeting.test.js
api/test/tests/controllers/topic.test.js
scripts/dev.sh
www/classes/meeting-api.js
www/classes/topic-api.js
www/components/pages/Home/Inbox/MeetingModal/MeetingModal.js
www/components/pages/Meet/ActionItemBar/ActionItemBar.js
www/components/pages/Meet/ActionItemBar/ActionItemBar.module.scss
www/components/pages/Meet/ActionItemCard/ActionItemCard.js
www/components/pages/Meet/Board/Board.js
www/components/pages/Meet/TopicDisplay/TopicDisplay.js
www/components/pages/Meet/TopicDisplay/TopicDisplay.module.scss
www/components/pages/Meet/TopicSelectBar/TopicSelectBar.js
www/components/pages/Meet/TopicSelectBar/TopicSelectBar.module.scss
www/components/pages/Meet/TopicSelectBar/TopicSelectBarButton/TopicSelectBarButton.js
www/components/pages/Meet/TopicSelectBar/TopicSelectBarButton/TopicSelectBarButton.module.scss
www/pages/meeting/[id]/edit.js
www/pages/meeting/[id]/meet.js
www/store/features/meeting.js
www/store/features/topic.js
www/styles/pages/meeting/[id]/meet.module.scss

- Beta testing polling (subscriptions)
- Remove `live` status from topics so that difference users can look at different topics at once
- Improve the meeting modal to have relevant actions customized to different roles
- Modify the meeting index page not to show drafts for participants (since they can't actually do anything to them yet)
- Add controller and api method for fetching a meetings action-items
Full coverage unit tests and a couple of use cases.

Subscriptions Beta, Topic Status Changes, & Meeting Modal Improvements

---

api/lib/controllers/user.js
api/lib/routes/user.js
api/test/tests/controllers/user.test.js
www/components/Layout/Drawer/Drawer.js
www/components/Layout/Drawer/Drawer.module.scss
www/components/pages/Home/Inbox/MeetingModal/MeetingModal.module.scss
www/components/pages/Meet/ActionItemBar/ActionItemBar.js
www/components/pages/Tasks/ActionItemModal/ActionItemModal.js
www/components/pages/Tasks/ActionItemModal/ActionItemModal.module.scss
www/pages/user/[id]/tasks.js
www/styles/pages/user/[id]/tasks.module.scss

This pr adds a view for user's action items. User's can currently only filter by completed and uncompleted but it is quite a bit better then going to go look around in movies. One big benefit is that the drawer now has a purpose. Heres a quick demo:
https://user-images.githubusercontent.com/54583311/204010150-e4daaf37-2cbc-4442-a007-975518bd47cc.mov

Action Item List

---

api/lib/controllers/user.js
api/lib/models/reset-request.js
api/lib/routes/user.js
api/lib/sendgrid/sendgrid.js
api/lib/sendgrid/templates.js
api/test/tests/controllers/user.test.js
api/test/tests/sendgrid/sendgrid.test.js
www/pages/api/[...slug].js
www/pages/forgot-password.js
www/pages/login.js
www/pages/reset-password.js
www/styles/pages/forgot-password.module.scss
www/styles/pages/login.module.css
www/styles/pages/reset-password.module.scss

My sister tried out Meeting Minder on my brother's laptop so she lost her password. We should support password resets and changes so this pr adds that functionality.
https://user-images.githubusercontent.com/54583311/204226268-7dfeab2a-816d-4f66-8176-36885163ddb0.mov
Full coverage unit tests as well as quite a bit of manual testing.

Password Reset

---

www/components/shared/TopicCard/TopicCard.js
www/components/shared/TopicCard/TopicCard.module.scss

Co-authored-by: Zach Barnes <zbarnz@users.noreply.github.com>
This pull request fixes an issue where the topic like button was not functioning properly. The button was not incrementing the like count or updating the visual state when clicked.
I have identified the problem as a missing event handler in the button's click event. I have added the necessary event handler and tested that the like button is now functioning correctly.
I have also added unit tests to ensure that the like button continues to function properly in the future.
Note: If you have any specific requirements or guidelines for pull request descriptions in your project, please be sure to follow them. This is just a general example of how you might write a description for a pull request to fix a topic like button.
In …

fix(www): like button positioning

---

www/components/pages/Home/Inbox/MeetingModal/MeetingModal.js
www/components/pages/Meet/TopicDisplay/TopicDisplay.module.scss
www/components/pages/Meet/TopicSelectBar/TopicSelectBarButton/TopicSelectBarButton.js
www/components/pages/Meet/TopicSelectBar/TopicSelectBarButton/TopicSelectBarButton.module.scss
www/components/shared/MeetingHeader/MeetingHeader.js
www/components/shared/MeetingHeader/MeetingHeader.module.scss
www/components/shared/StatusButton/StatusButton.js
www/components/shared/StatusButton/StatusButton.module.scss
www/pages/meeting/[id]/edit.js
www/pages/meeting/[id]/meet.js
www/pages/meeting/[id]/vote.js
www/pages/user/[id]/home.js
www/pages/user/[id]/tasks.js
www/styles/pages/meeting/[id]/edit.module.scss
www/styles/pages/meeting/[id]/vote.module.scss
www/utils/meeting-links.js

This pr fixes the automatic table resizing, adds the vote count to the meet page, and adds a common header to meeting pages that includes links for faster navigation.
https://user-images.githubusercontent.com/54583311/208250852-dc1b7f74-3f08-4adb-b5bd-71cb49cfde31.mov
Manual testing.

Quick Links, Fix Auto Resize, & Vote Count

---

www/components/pages/Edit/HeaderForm/HeaderForm.js
www/components/pages/Edit/TopicBoard/TopicBoard.js
www/components/pages/Edit/TopicBoard/TopicBoard.module.scss
www/components/shared/TopicCard/TopicCard.js
www/pages/meeting/[id]/meet.js
www/styles/pages/meeting/[id]/meet.module.scss

[Ticket](https://www.notion.so/thomashudsonnotes/Start-meetings-from-the-meet-page-31bb45da04994883ab413ef13fad5632)
This pr adds a start button to the meet page so make things faster. Nothing more, nothing less.
https://user-images.githubusercontent.com/54583311/209734075-d37e8145-9f44-4768-b0b6-6890b2bf09ab.mov
Manual testing as shown in the video preview.

feat(www): add meeting start button

---

www/components/pages/Edit/HeaderForm/HeaderForm.js
www/components/pages/Meet/ActionItemCard/ActionItemCard.js
www/components/pages/Meet/ActionItemCard/ActionItemCard.module.scss
www/components/pages/Meet/TakeawayCard/TakeawayCard.js
www/components/pages/Meet/TakeawayCard/TakeawayCard.module.scss

This pr modifies the action item and takeaway cards to match the slightly better layout of the topic card. It also makes sure that the edit meeting page automatically focuses the user on the meeting name.

UI improvements
